### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by MrModest** [DallasHoff/glance-extensions#1]
Hey, thanks for these extensions!

I wish to use it in my working Mac laptop, but running a background node server can mess up with my daily work staff.

Do you consider adding a Dockerfile and push the image into Docker Hub or GitHub registry? :)

**Comment by DallasHoff** [comment]
Sure, that wouldn't be too difficult.

**Comment by DallasHoff** [comment]
I've got the Dockerfile added. I'll also see about the registry soon.

**Comment by MrModest** [comment]
That's working! Thank you!

---

This is how I added it into compose file:

I have just learned today that you can use git repo directly in your compose file. So, even an image in the Docker Hub isn't required :D 
```yml
  todoist-ext:
    build:
      context: https://github.com/DallasHoff/glance-extensions.git#6c194df74e5e3e2514240b24c5be12925e01c4a4
      dockerfile: Dockerfile
    container_name: todoist-ext
    hostname: todoist-ext
    environment:
      - TODOIST_TOKEN=<todoist token here>
```
`6c194df74e5e3e2514240b24c5be12925e01c4a4` here is just a commit SHA to fix version. For "latest" you can use just `main` instead

and the config in glance:

```yml
- type: extension
  title: To Do
  title-url: https://app.todoist.com/
  cache: 1s
  url: http://todoist-ext:8080/todoist # use service name since the extension in the same compose file with the glance
  allow-potentially-dangerous-html: true
  parameters:
    filter: '(Overdue | Today) & (workspace: Work | @💼 WorkTime)'
```

Happy to see that it works fine even with emojis in the filter :)
